# Whenever a tag push matching pattern "v*" then run the job
on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create export directory
        run: mkdir html5

      - name: Godot HTML5 export
        uses: dulvui/godot-html-export@v1
        with:
          godot-version: 4.3
          create-export-preset-cfg: true
